import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  wrapper: {
    backgroundColor: '#F5F6F8',
    flex: 1,
  },
  container: {
    paddingTop: 30,
    paddingEnd: 20,
    paddingStart: 20,
    minHeight: 910,
  },
  card: {
    backgroundColor: '#FFF',
    borderRadius: 16,
    padding: 25,
    marginBottom: 40,
    flexWrap: 'wrap',
  },
  title: {
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 32,
    color: '#4E4B66',
  },
  UserImage: {
    marginTop: 35,
    marginHorizontal: 60,
    resizeMode: 'contain',
    width: 150,
    height: 150,
    borderRadius: 300 / 2,
    overflow: 'hidden',
    borderWidth: 0.5,
    borderColor: ' rgba(73, 83, 99, 0.24)',
  },
  userName: {
    fontWeight: '600',
    fontSize: 20,
    lineHeight: 34,
    color: '#14142B',
    textAlign: 'center',
    padding: 10,
    top: 20,
  },
  userDetail: {
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 24,
    color: '#4E4B66',
    textAlign: 'center',
    padding: 10,
    top: 10,
  },
  lineStyle: {
    borderWidth: 0.5,
    borderColor: '#DEDEDE',
    marginTop: 30,
    width: 320,
    marginHorizontal: -25,
  },
  button: {
    marginTop: 20,
    height: 56,
    width: 187,
    backgroundColor: '#5F2EEA',
    borderRadius: 16,
    alignSelf: 'center',
  },
  buttonText: {
    textAlign: 'center',
    paddingVertical: 12,
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 28,
    color: '#F7F7FC',
  },
  titleMenu: {
    fontSize: 18,
    fontWeight: '600',
    lineHeight: 34,
    color: '#14142B',
    paddingBottom: 20,
  },
  lineStyle1: {
    borderWidth: 0.5,
    borderColor: '#DEDEDE',
    marginTop: 5,
    marginBottom: 40,
    width: 275,
    alignSelf: 'center',
  },
  inputWrapper: {
    // marginHorizontal: 10,
  },
  inputlabel: {
    paddingBottom: 5,
    color: '#4E4B66',
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 20,
  },
  input: {
    width: 275,
    height: 48,
    backgroundColor: '#FCFDFE',
    marginBottom: 20,
    marginTop: 5,
    borderWidth: 1,
    padding: 10,
    borderColor: '#DEDEDE',
    borderRadius: 8,
    color: '#4E4B66',
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 24,
  },
  prefix: {
    bottom: -15,
    paddingStart: 10,
    color: 'grey',
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 24,
    borderEndWidth: 1,
    borderEndColor: 'grey',
  },
  input1: {
    top: -15,
    width: 275,
    height: 48,
    marginBottom: 20,
    borderWidth: 1,
    padding: 10,
    // backgroundColor: '#FCFDFE',
    borderColor: '#DEDEDE',
    borderRadius: 8,
    color: '#4E4B66',
    paddingHorizontal: 50,
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 24,
  },
  buttonUpdate: {
    top: -20,
    marginTop: 20,
    height: 48,
    width: 325,
    backgroundColor: '#5F2EEA',
    borderRadius: 16,
    marginBottom: 40,
  },
  buttonUpdateText: {
    textAlign: 'center',
    paddingVertical: 8,
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 28,
    color: '#F7F7FC',
  },

  //MODAL
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  buttonModal: {
    borderRadius: 20,
    padding: 10,
    elevation: 2,
  },
  buttonModalOpen: {
    backgroundColor: '#F194FF',
  },
  buttonModalClose: {
    backgroundColor: '#2196F3',
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalText: {
    marginBottom: 15,
    textAlign: 'center',
  },
});
