import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  wrapper: {
    backgroundColor: '#E5E5E5',
    flex: 1,
  },
  container: {
    paddingTop: 30,
    paddingEnd: 20,
    paddingStart: 20,
    minHeight: 910,
  },
  title: {
    fontSize: 18,
    fontWeight: '600',
    lineHeight: 24,
    color: '#14142B',
    paddingBottom: 15,
  },
  card: {
    backgroundColor: '#FFF',
    borderRadius: 16,
    padding: 25,
    marginBottom: 40,
    flexWrap: 'wrap',
    display: 'flex',
    flexDirection: 'row',
  },
  methodBorder: {
    borderColor: '#BABABA',
    borderWidth: 1,
    height: 30,
    width: 60,
    borderRadius: 8,
    marginHorizontal: 15,
    marginVertical: 5,
  },
  method: {
    alignSelf: 'center',
    padding: 5,
    resizeMode: 'contain',
    width: 30,
    height: 30,
  },
  method1: {
    alignSelf: 'center',
    margin: 6,
    resizeMode: 'contain',
    width: 15,
    height: 15,
  },
  viewMoreWrapper: {
    display: 'flex',
    flexDirection: 'row',
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  viewMoreLine: {
    borderWidth: 0.5,
    borderColor: '#DEDEDE',
    width: '40%',
    height: 1,
    bottom: -3,
  },
  viewMoreText: {
    alignSelf: 'center',
    marginHorizontal: 20,
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 24,
    color: '#A0A3BD',
  },
  wrapperOption: {
    display: 'flex',
    flexDirection: 'row',
    marginHorizontal: 55,
  },
  pay: {
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 24,
    color: '#6E7191',
    marginEnd: 5,
  },
  see: {
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 26,
    color: '#5F2EEA',
  },
  inputWrapper: {
    marginHorizontal: 10,
  },
  inputlabel: {
    // top: 15,
    paddingBottom: 5,
    color: '#696F79',
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 24,
  },

  input: {
    width: 250,
    height: 40,
    marginBottom: 20,
    marginTop: 5,
    borderWidth: 1,
    padding: 10,
    borderColor: '#DEDEDE',
    borderRadius: 8,
    color: '#4E4B66',
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 24,
  },
  prefix: {
    bottom: -11,
    paddingStart: 10,
    color: 'grey',
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 24,
    borderEndWidth: 1,
    borderEndColor: 'grey',
  },
  //   lineV: {
  //     bottom: -20,
  //     height: 20,
  //     borderLeftWidth: 1,
  //   },
  input1: {
    top: -15,
    width: 250,
    height: 40,
    marginBottom: 20,
    borderWidth: 1,
    padding: 10,
    borderColor: '#DEDEDE',
    borderRadius: 8,
    color: '#4E4B66',
    paddingHorizontal: 50,
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 24,
  },
  button: {
    width: '100%',
    height: 50,
    backgroundColor: '#5F2EEA',
    borderRadius: 12,
    padding: 12,
    marginBottom: 40,
  },
  buttontext: {
    textAlign: 'center',
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 28,
  },
  alert: {
    marginHorizontal: 10,
    width: 250,
    height: 50,
    borderRadius: 8,
    padding: 12,
    marginBottom: 10,
    backgroundColor: 'rgba(244, 183, 64, 0.3)',
  },
  alertText: {
    textAlign: 'center',
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 24,
  },
});
