import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  wrapper: {
    backgroundColor: '#F5F6F8',
    flex: 1,
  },
  container: {
    paddingTop: 40,
    paddingEnd: 20,
    paddingStart: 20,
    minHeight: 910,
  },
  title: {
    fontSize: 18,
    fontWeight: '600',
    lineHeight: 34,
    color: '#14142B',
    paddingBottom: 20,
  },
  card1: {
    backgroundColor: '#FFF',
    borderRadius: 16,
    paddingHorizontal: 15,
    paddingVertical: 25,
    marginBottom: 40,
    // maxHeight: 400,
    // flex: 1,
    // marginHorizontal: 16,
  },
  card: {
    backgroundColor: '#FFF',
    borderRadius: 16,
    padding: 25,
    marginBottom: 40,
    // maxHeight: 400,
    // flex: 1,
    // marginHorizontal: 16,
  },
  screenline: {
    bottom: -25,
    backgroundColor: '#9570FE',
    borderRadius: 3,
  },
  screenlineText: {
    fontSize: 12,
    color: 'white',
    textAlign: 'center',
  },
  seatWrapper: {
    paddingTop: 20,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  greenline: {
    bottom: -5,
    borderWidth: 0.5,
    height: 145,
    right: -2,
    borderColor: '#00BA88',
  },
  seat: {
    bottom: -25,
    borderWidth: 1,
    width: '45%',
    height: 100,
  },
  lineWrapper: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    top: -20,
  },
  redline: {
    bottom: -25,
    borderWidth: 0.5,
    width: 120,
    marginHorizontal: 20,
    borderColor: '#ED2E7E',
    marginBottom: 30,
  },
  seatingKey: {
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 28,
    color: '#000',
  },
  wrapperKey: {
    marginTop: 15,
    display: 'flex',
    flexDirection: 'row',
    maxWidth: 230,
    flexWrap: 'wrap',
  },
  key: {
    display: 'flex',
    flexDirection: 'row',
    paddingEnd: 35,
    paddingBottom: 15,
    alignSelf: 'flex-start',
    fontSize: 13,
    fontWeight: '400',
    lineHeight: 22,
    color: '#4E4B66',
  },
  keyNumber: {
    right: -16,
    display: 'flex',
    flexDirection: 'row',
    paddingEnd: 35,
    paddingBottom: 15,
    alignSelf: 'flex-start',
    fontSize: 13,
    fontWeight: '400',
    lineHeight: 22,
    color: '#4E4B66',
  },
  desc: {
    paddingStart: 10,
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 22,
    color: '#4E4B66',
  },
  smallBox1: {
    width: 20,
    height: 20,
    backgroundColor: '#D6D8E7',
    borderRadius: 4,
  },
  smallBox2: {
    width: 20,
    height: 20,
    backgroundColor: '#5F2EEA',
    borderRadius: 4,
  },
  smallBox3: {
    width: 20,
    height: 20,
    backgroundColor: '#6E7191',
    borderRadius: 4,
  },
  resetBtn: {
    color: '#5F2EEA',
  },
  cinema: {
    bottom: -25,
    fontSize: 45,
    fontWeight: '800',
    height: 60,
    alignSelf: 'center',
    color: '#5F2EEA',
  },
  cinemaName: {
    fontSize: 24,
    fontWeight: '600',
    lineHeight: 34,
    color: '#14142B',
    textAlign: 'center',
    paddingTop: 35,
  },
  movieTitle: {
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 24,
    color: '#14142B',
    textAlign: 'center',
    paddingTop: 10,
    marginBottom: 35,
  },
  orderInfo: {
    display: 'flex',
    flexDirection: 'row',
    paddingBottom: 20,
  },
  info1: {
    flex: 2,
    color: '#6B6B6B',
  },
  info2: {
    flex: 1,
    textAlign: 'right',
    color: '#14142B',
  },
  lineStyle: {
    borderWidth: 0.5,
    borderColor: '#DEDEDE',
    marginTop: 30,
    width: '140%',
    alignSelf: 'center',
    right: -20,
    left: -20,
  },
  totalWrapper: {
    paddingTop: 25,
    display: 'flex',
    flexDirection: 'row',
    paddingBottom: 20,
  },
  totalName: {
    flex: 3,
    fontSize: 18,
    fontWeight: '600',
    lineHeight: 34,
    color: '#000',
  },
  totalValue: {
    textAlign: 'right',
    flex: 4,
    fontSize: 24,
    fontWeight: '700',
    lineHeight: 30,
    color: '#5F2EEA',
  },
  button: {
    width: '100%',
    height: 56,
    backgroundColor: '#5F2EEA',
    borderRadius: 12,
    padding: 12,
    marginBottom: 40,
  },
  buttontext: {
    textAlign: 'center',
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 28,
  },
  //Seat
  container1: {
    flex: 1,
    marginHorizontal: 0,
  },
  containerSeat: {
    backgroundColor: 'white',
    borderRadius: 8,
    marginTop: 45,
    // paddingTop: 20,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  resetBox: {
    width: 40,
    height: 20,
    backgroundColor: '#D6D8E7',
    borderRadius: 4,
    left: 20,
    textAlign: 'center',
    paddingHorizontal: 3,
    paddingVertical: 2,
  },
});
