import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  wrapper: {
    backgroundColor: '#FFFFFF',
    flex: 1,
  },
  container: {
    paddingTop: 50,
    paddingEnd: 20,
    paddingStart: 20,
    minHeight: 910,
  },
  card: {
    borderColor: '#DEDEDE',
    borderWidth: 2,
    borderRadius: 8,
    justifyContent: 'center',
    alignSelf: 'center',
    maxWidth: 223,
    maxHeight: 308,
  },
  movieimg: {
    margin: 30,
    resizeMode: 'contain',
    height: '80%',
    alignSelf: 'center',
  },
  title: {
    fontSize: 20,
    fontWeight: '600',
    lineHeight: 32,
    textAlign: 'center',
    color: '#000',
    paddingTop: 30,
    marginBottom: 20,
  },
  category: {
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 32,
    textAlign: 'center',
    color: '#4E4B66',
  },
  wrapperdetail: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    paddingTop: 30,
  },
  left: {
    flex: 1,
  },
  right: {
    flex: 1,
  },
  name: {
    fontSize: 13,
    fontWeight: '400',
    lineHeight: 22,
    color: '#8692A6',
  },
  value: {
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 28,
    color: '#121212',
  },
  lineStyle: {
    borderWidth: 0.5,
    borderColor: '#DEDEDE',
    marginTop: 35,
  },
  synopsisname: {
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 28,
    color: '#14142B',
    paddingBottom: 15,
    paddingTop: 20,
  },
  synopsisvalue: {
    fontSize: 13,
    fontWeight: '400',
    lineHeight: 22,
    color: '#4E4B66',
  },
  wrapperShowTime: {
    backgroundColor: '#F5F6F8',
    paddingTop: 50,
    paddingEnd: 20,
    paddingStart: 20,
  },
  showtimeTitle: {
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 34,
    color: '#000',
    textAlign: 'center',
    paddingBottom: 20,
  },
  input: {
    borderRadius: 4,
    backgroundColor: '#EFF0F6',
    width: '100%',
    height: 48,
    color: '4E4B66',
    fontSize: 14,
    fontWeight: '600',
    padding: 5,
    marginBottom: 10,
  },
  scheduleCard: {
    marginTop: 40,
    backgroundColor: '#FFF',
    padding: 25,
    borderRadius: 8,
  },
  cinema: {
    alignSelf: 'center',
  },
  cinemaLocation: {
    paddingTop: 15,
    textAlign: 'center',
  },
  timeWrapper: {
    paddingTop: 15,
    display: 'flex',
    flexDirection: 'row',
    maxWidth: 270,
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  time: {
    paddingBottom: 10,
    fontWeight: '400',
    fontSize: 12,
    color: '#4E4B66',
    marginHorizontal: 5,
  },
  priceWrapper: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 15,
  },
  priceName: {
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 24,
    color: '#6B6B6B',
  },
  priceValue: {
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 26,
    color: '#000',
  },
  button: {
    marginTop: 25,
    width: '100%',
    height: 40,
    backgroundColor: '#5F2EEA',
    borderRadius: 8,
  },
  buttonText: {
    textAlign: 'center',
    padding: 6,
    color: '#FFFFFF',
    fontSize: 14,
    lineHeight: 24,
    fontWeight: '700',
  },
  viewMoreWrapper: {
    display: 'flex',
    flexDirection: 'row',
    paddingVertical: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  viewMoreLine: {
    borderWidth: 0.5,
    borderColor: '#DEDEDE',
    width: '35%',
    height: 1,
    bottom: -3,
  },
  viewMoreText: {
    alignSelf: 'center',
    marginHorizontal: 15,
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 26,
    color: '#5F2EEA',
  },
});
